FROM rust:1.67 as builder

COPY Cargo.lock Cargo.toml
RUN cargo fetch
COPY src ./src
RUN cargo build --release

FROM debian:buster-slim
WORKDIR /usr/src/minecraft-honeypot
COPY --from=builder /usr/src/minecraft-honeypot/target/release/minecraft_tcp_honeypot /usr/local/bin/minecraft-honeypot

EXPOSE 25565

cmd[ "minecraft-honeypot" ]